apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-conf
data:
  fluent.conf: |
    <source>
        @type forward
        port 24224
        bind 0.0.0.0
    </source>
    <match **>
        @type cloudwatch_logs
        log_group_name <LOG GROUP NAME>
        log_stream_name "#{Socket.gethostname}"
        auto_create_stream true
        region <REGION>
    </match>
