apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-conf
data:
  fluent-bit.conf: |
    [SERVICE]
        flush            1
        log_Level        info
        daemon           off
        parsers_File     parsers.conf
        http_server      on
        http_listen      0.0.0.0
        http_port        2020
        storage.metrics  on

    [INPUT]
        Name        tail
        Path        /var/log/nginx/access.log
        Parser      nginx

    [FILTER]
        Name         parser
        Match        *
        Key_Name     log
        Parser       nginx
        Reserve_Data true
    
    [OUTPUT]
        Name        kafka
        Match       *
        Brokers     <broker clients>
        Topics      nginx_logs

    [OUTPUT]
        Name        stdout
        Match       *
  
  parsers.conf: |
    [PARSER]
        Name        nginx
        Format      regex
        Regex       ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")
        Time_Key    time
        Time_Format %d/%b/%Y:%H:%M:%S %z
